- task: TerraformTask@5
- task: AzureCLI@2
  inputs:
    scriptType: 'ps'
    scriptLocation: 'inlineScript'
    inlineScript: 'az login --service-principal -u d4598acc-c1ea-4e73-be8e-9a93061fbc4a -p 8*$24p(!UVQJf"sy --tenant 8b255d37-387e-40db-a9af-f7007793050a'
  inputs:
    provider: 'azurerm'
    command: 'init'
- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'validate'
- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'plan'
- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'apply'